# Generated by Django 4.0.3 on 2023-09-18 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField()),
                ('parent_twit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.twit')),
            ],
        ),
    ]
