# Generated by Django 4.0.3 on 2023-09-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twit',
            old_name='parent_twit',
            new_name='parent',
        ),
    ]
