# Generated by Django 4.0.3 on 2023-09-19 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_twit_author_alter_twit_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='twitter.twit'),
        ),
    ]
