# Generated by Django 4.0.3 on 2023-09-20 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_alter_twit_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='twitter.twit'),
        ),
    ]
