# Generated by Django 4.0.3 on 2023-09-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_twit_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twit',
            name='child',
        ),
    ]
